name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # BUILD BACKEND
      # -------------------------
      - name: Build Backend
        working-directory: "./webapp/backend"
        run: |
          docker build -t webapp-backend .

      # -------------------------
      # BUILD FRONTEND
      # -------------------------
      - name: Build Frontend
        working-directory: "./webapp/frontend"
        run: |
          docker build -t webapp-frontend .
